### ISSUE TITLE
since refacoring of ClassLoaderResourceAccessor in 4..0.0-beta2, searchPath "classpath*:" is not handled anymore correctly

### ISSUE THREAD

**Issue by chadoc** [liquibase/liquibase#1595]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: spring-boot 2.3.7.RELEASE

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Postgres (but doesn't matter)

**Operating System Type & Version**: Linux mint (but doesn't matter)

## Description
includeAll in a spring-boot project with a searchPath containing a "classpath*:" doesn't find anything.

## Steps To Reproduce
Define an "includeAll" task in a spring boot project with a searchPath set to "classpath*:db/changelog" and changelog files available on the searchPath failed because not found
`

* includeAll:
        path: classpath*:db/changelog
`

## Actual Behavior
Doesn't find changelogs

## Expected/Desired Behavior
Should find changelog to include

## Screenshots (if appropriate)
* 

## Additional Context
Problem comes from SpringResourceAccessor.finalizeSearchPath method which expect to always have "classpath:classpath:" and in that case, path is "classpath:classpath*:" so not replaced.

https://github.com/liquibase/liquibase/blob/aae1f015540f2a814b7a9e3d7b4db2fa465e9a23/liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java#L157

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1060) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.3.2

**Comment by chadoc** [comment]
After having tested different version, it looks the issue was introduced by the refactoring of ClassLoaderResourceAccessor already in 4.0.0-beta2:

https://github.com/liquibase/liquibase/blob/bfabfdf1de9b954f2d4a2a792d5377ba88062273/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L219

**Comment by molivasdat** [comment]
Hi @chadoc Thank you for bringing this to our attention.  Since you have identified the code that was changed, if you have a suggested fix, you can create a PR and reference this issue.

**Comment by oleksanderkorn** [comment]
I have similar issue. I am using Spring Boot and Liquibase. And I have defined changelog file as following:
```
databaseChangeLog:
  - includeAll:
      path: db/changelog/0.0.1

```
When I use `liquibase-core` version `4.0.0` it works as expected, and changelog files inside `db/changelog/0.0.1` are found and applied correctly:
![image](https://user-images.githubusercontent.com/9252017/103648778-adb7f880-4f5d-11eb-8ff1-a202d605e360.png)
When I only change version to `4.2.2` the resolved path is now absolute and starts with `file:` and `changeLogStream` is null:
![image](https://user-images.githubusercontent.com/9252017/103648941-f079d080-4f5d-11eb-9a47-486f2aa7d5c9.png)

**Comment by dekar91** [comment]
Same as @oleksanderkorn. Liqubase 4.0.0 works fine, but 4.2.2 creates an ampty stream.
OpenJdk 15, Windows 10.

**Comment by tecaz** [comment]
Similar setup to @oleksanderkorn (`includeAll` + `path` + `relativeToChangelogFile`), can confirm 4.1.0 is the last version to work as expected, 4.1.1 and the 4.2.x branch all end up in "File was not found in Spring resources" errors.

**Comment by nvoxland** [comment]
That should have continued to work, I'll try to replicate it and debug it to see what is going on.

**Comment by nvoxland** [comment]
PR #1664 should fix this.

**Comment by nikomiranda** [comment]
Still not working on 4.3.1.

SpringResourceAccessor:168 replaces the classpath*: then spring is not searching on all jars.

```
    protected String finalizeSearchPath(String searchPath) {
        searchPath = "classpath:"+searchPath;
        searchPath = searchPath
                .replaceAll("classpath\\*:", "classpath:")     // <----- LINE 168 
                .replace("\\", "/")
                .replaceAll("//+", "/")
                .replace("classpath:classpath:", "classpath:");

        return searchPath;
    }
```

**Comment by nvoxland** [comment]
The plan was to standardize down to `classpath:` for historical reasons, then actually use classpath* for searching all the time, but apparently that part got lost in some of the other work I was doing. Sorry.

I pushed a new version as #1698 that should handle it better. I'm just using `classpath*:` as the search path all the time, since that seems to better match what we actually want to do with the ResourceAccessor logic in general.

Can you take a look at that PR and see if it works for you, @nikomiranda?

**Comment by nikomiranda** [comment]
@nvoxland I can confirm that pull request is working well for me using classpath*:changelogs and it's finding changelogs inside  several jars (Spring 5.3.x no boot)

Looks okey

**Comment by nvoxland** [comment]
Great, thanks for checking @nikomiranda  We'll get it merged in for 4.3.2
