### ISSUE TITLE
Bad sql generated for dropColumn changeset for MSSQL

### ISSUE THREAD

**Issue by AlexanderSashchenko** [liquibase/liquibase#1818]
## Environment
**Liquibase Version**:4.3.X

**Liquibase Integration & Version**: test-harness

**Liquibase Extension(s) & Version**: na

**Database Vendor & Version**: MSSQL 2017

**Operating System Type & Version**: Windows 10

## Description
While testing general set of tests at test-harness I found that new liquibase core version 4.3.X generates wrong sql for mssql for dropColumn changeset. At the same time previous version of liquibase core generates correct sql.

## Steps To Reproduce
Run dropColumn changeset against MSSQL 2017 using liquibase 4.3.X version.
Drop column changeset used for the test:
`<changeSet author="oleh" id="1">
            <addColumn tableName="posts">
                <column name="varcharColumn" type="varchar(25)" value="INITIAL_VALUE"/>
            </addColumn>
            <dropColumn tableName="posts" columnName="varcharColumn"/>
            <rollback/>
        </changeSet>`
As you see we are trying to add columnt and then drop it:

## Actual Behavior
**Actual sql generated:**
_ALTER TABLE posts ADD varcharColumn varchar(25)
UPDATE posts SET varcharColumn = 'INITIAL_VALUE'
DECLARE sql [nvarchar](MAX)
SELECT sql = N'ALTER TABLE posts DROP CONSTRAINT ' + QUOTENAME([df].[name]) FROM [sys].[columns] AS [c] INNER JOIN [sys].[default_constraints] AS [df] ON [df].[object_id] = [c].[default_object_id] WHERE [c].[object_id] = OBJECT_ID(N'posts') AND [c].[name] = N'varcharColumn'
EXEC sp_executesql sql
ALTER TABLE posts DROP COLUMN varcharColumn_
Obviously the part between "UPDATE posts..." and ALTER TABLE posts" shouldn't be present in a resulting query;

## Expected/Desired Behavior
**Expected sql generated:**
_ALTER TABLE posts ADD varcharColumn varchar(25)
UPDATE posts SET varcharColumn = 'INITIAL_VALUE'
ALTER TABLE posts DROP COLUMN varcharColumn_

**Comment by kataggart** [comment]
based on comments in https://github.com/liquibase/liquibase/issues/1818 this was resolved via that PR

**Comment by KushnirykOleh** [comment]
@kataggart my PR is test-harness didn't resolve issue, however this can be expected behavior if we want to drop column together with related constraints. Need someone to look at this issue and confirm this is correct query generation for dropColumn changeType

**Comment by nvoxland** [comment]
@KushnirykOleh This is the correct behavior. Although not necessarily all constraints. 

When we do <dropColumn>, people usually think of default values as not something separate from the column and so not something they have to manually remove first. Alol the other databases work that way, so which makes for a behavior difference with <dropColumn>. So we make sure to drop the default value first. Same with not null constraints or unique constraints.

But, something like a foreign key constraint which spans objects and tends to be treated as an independent thing across databases is different, and we don't try to automatically drop those first.

So I'll close this as "by design"
