### ISSUE TITLE
liquibase.exception.ChangeLogParseException: 301 Moved Permanently

### ISSUE THREAD

**Issue by gmanwadkar** [liquibase/liquibase#2448]
## Environment

**Liquibase Version**: dbchangelog-4.0.xsd

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
Error while starting the server. XSD file http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd

liquibase.exception.ChangeLogParseException: Error parsing line 2 column 35 of db/rt/mws_changelog.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.

## Actual Behavior

Error starting an application

## Expected/Desired Behavior

No exception

**Comment by mohnishanjaria** [comment]
Standing in the same line again. This is the second or third time we are facing similar issues in recent times...

### **Please provide a permanent fix for this! We are facing a lot of downtime due to this issue**


`Unexpected error running Liquibase: Error parsing line 2 column 35 of migration/schema_v1auth-schema-v1.changelog-master.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.`

**Comment by KarlJohnsonIntrepid** [comment]
Any fix would be greatly appreciated, all our application builds that use Liquibase are failing. It appears that the URL http://www.liquibase.org/xml/ns/dbchangelog is being 301 redirected to http://www.liquibase.org/xml/ns/dbchangelog/ which may be the cause of the isssue

**Comment by bbr88** [comment]
@KarlJohnsonIntrepid, upgrading to the liquibase-core:4.3.5 solved this issue for me.

**Comment by lbanas** [comment]
I changed ulr address in head XML from http to https
https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd
and it help

**Comment by KarlJohnsonIntrepid** [comment]
thanks @bbr88  upgrading to liquibase-core:4.3.5 solved it for me aswell

**Comment by AleksanderGrzybowski** [comment]
Hey, we're experiencing the same issue on multiple projects. We can't quickly upgrade liquibase and redeploy hundreds of services, is there any workaround for this (other than disabling migrations) for the time being? Thanks for a great product nonetheless :) 

```
 0:57:38.922 INFO  [liquibase.integration.commandline.Main]: Starting Liquibase at Tue, 01 Feb 2022 10:57:38 GMT (version 3.8.9 #73 built at Mon Apr 06 09:32:58 UTC 2020)                              │
10:57:39.369 INFO  [liquibase.integration.commandline.Main]: No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro f │
10:57:39.369 INFO  [liquibase.integration.commandline.Main]: Liquibase Community 3.8.9 by Datical                                                                                                       │
10:57:39.822 INFO  [com.github.blagerweij.sessionlock.PGLockService]: Successfully acquired change log lock                                                                                             │
10:57:41.145 ERROR [liquibase.parser.core.xml.XMLChangeLogSAXParser$1]: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. │
10:57:41.147 INFO  [com.github.blagerweij.sessionlock.PGLockService]: Successfully released change log lock                                                                                             │
10:57:41.153 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo │
liquibase.exception.ChangeLogParseException: Error parsing line 2 column 35 of db.changelog.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo │
    at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:120)                                                                                                      │
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)                                                                                                         │
    at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)                                                                                                                                     │
    at liquibase.Liquibase.update(Liquibase.java:190)                                                                                                                                                   │
    at liquibase.Liquibase.update(Liquibase.java:179)                                                                                                                                                   │
    at liquibase.integration.commandline.Main.doMigration(Main.java:1643)                                                                                                                               │
    at liquibase.integration.commandline.Main.run(Main.java:302)                                                                                                                                        │
    at liquibase.integration.commandline.Main.main(Main.java:162)                                                                                                                                       │
Caused by: org.xml.sax.SAXParseException: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.  │
    at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)                                                                       │

```

**Comment by BEllis** [comment]
A workaround for the issue is to update the new location in the XML files (in our case we're using v 3.6, you should keep the same version you are currently using) from,

xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd"

to

xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http**s**://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http**s**://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd"

Note: You are only updating every other URL to https (the url before is the namespace and this is unchanged).

**Comment by BEllis** [comment]
I've been told there is a liquibase.prefer.internal.xsd property that can be used as well (only available in 3.10.* onwards). I've not tried this myself though.

**Comment by abhirathod** [comment]
> Hey, we're experiencing the same issue on multiple projects. We can't quickly upgrade liquibase and redeploy hundreds of services, is there any workaround for this (other than disabling migrations) for the time being? Thanks for a great product nonetheless :)
> 
> ```
>  0:57:38.922 INFO  [liquibase.integration.commandline.Main]: Starting Liquibase at Tue, 01 Feb 2022 10:57:38 GMT (version 3.8.9 #73 built at Mon Apr 06 09:32:58 UTC 2020)                              │
> 10:57:39.369 INFO  [liquibase.integration.commandline.Main]: No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro f │
> 10:57:39.369 INFO  [liquibase.integration.commandline.Main]: Liquibase Community 3.8.9 by Datical                                                                                                       │
> 10:57:39.822 INFO  [com.github.blagerweij.sessionlock.PGLockService]: Successfully acquired change log lock                                                                                             │
> 10:57:41.145 ERROR [liquibase.parser.core.xml.XMLChangeLogSAXParser$1]: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. │
> 10:57:41.147 INFO  [com.github.blagerweij.sessionlock.PGLockService]: Successfully released change log lock                                                                                             │
> 10:57:41.153 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo │
> liquibase.exception.ChangeLogParseException: Error parsing line 2 column 35 of db.changelog.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo │
>     at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:120)                                                                                                      │
>     at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)                                                                                                         │
>     at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)                                                                                                                                     │
>     at liquibase.Liquibase.update(Liquibase.java:190)                                                                                                                                                   │
>     at liquibase.Liquibase.update(Liquibase.java:179)                                                                                                                                                   │
>     at liquibase.integration.commandline.Main.doMigration(Main.java:1643)                                                                                                                               │
>     at liquibase.integration.commandline.Main.run(Main.java:302)                                                                                                                                        │
>     at liquibase.integration.commandline.Main.main(Main.java:162)                                                                                                                                       │
> Caused by: org.xml.sax.SAXParseException: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.  │
>     at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)                                                                       │
> ```
I am attaching an exact change that needs to be done to resolve the issue.

- No Version or jar upgrade is required.
- Make this change to respective change-log files which will be executed. 

![image](https://user-images.githubusercontent.com/2970391/151978756-0b6505ed-15c6-4204-98e6-143fb5d96b00.png)

**Comment by kataggart** [comment]
Thanks everyone for the details. We are looking into this and will get back to you all soon. Promise. :) Thanks again for being such a great Community!

**Comment by kataggart** [comment]
https://github.com/liquibase/liquibase/issues/2449 (same issue, folks can also follow there)

**Comment by molivasdat** [comment]
Hi @gmanwadkar @mohnishanjaria @KarlJohnsonIntrepid @bbr88 @AleksanderGrzybowski @BEllis @abhirathod This issue has been fixed.
A permanent solution is to update your version of Liquibase which looks locally at the xsd files in the jar file.
Which version of Liquibase are you using?

**Comment by AleksanderGrzybowski** [comment]
Sure, I'll plan the update. The version is in the first line of stacktrace I posted before. Thanks for your support!

**Comment by nvoxland** [comment]
Closing since this has been resolved.

**Comment by davidyscott** [comment]
Hi folks,
It appears this issue is back...  I'm trying to use liquibase in a Spring/Gradle project.  I have the latest available maven dependency (`"org.liquibase:liquibase-core:4.8.0"`).

My root changelog has the following (as you can see, I've even tried setting the urls to https):
```
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.8.0.xsd">
```
but now my service fails to start up, with
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: Error parsing line 2 column 35 of classpath:/liquibase-root-changelog.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
```
