### ISSUE TITLE
Liquibase not able to create snapshot of a table if one more table with same name but with different case exists in that schema/catalog.

### ISSUE THREAD

**Issue by aayushi095** [liquibase/liquibase#2911]
## Environment

liquibase-core and Oracle Database.
** Liquibase Version:**
From version 3.5.3 to 4.11.0
** Liquibase Integration & Version:**
spring boot 5.3.19, spring boot 5.3.20
** Liquibase Extension(s) & Version:**

** Database Vendor & Version:**
Oracle 12c Windows
** Operating System Type & Version:**
Windows 10

## Description

Liquibase not able to create snapshot of tables having same name but different cases existing in a schema/catalog.
Due to which DatabaseChangeLog.getChangeSets() is null.

## Steps To Reproduce
**Case 1**
1. Create two tables with same name but with different cases in a case-sensitive database(say "demo" and "DEMO").
2. Try to create snapshot of "demo" table.
3. Check DatabaseChangeLog.getChangeSets(). It will return a null or size zero(0) change set.

**Case 2**
1. Create two tables with same name but with different cases in a case-sensitive database(say "demo" and "DEMO").
2. Try to create snapshot of "DEMO" table. This time it will be successfull. And DatabaseChangeLog.getChangeSets() is not null.
3. On calling getColumns() method of CreateTableChange, instead of returning columns of "DEMO" table it is returning columns of both the tables "demo" and "DEMO".

**But if we delete the other table from the databse and now there is only one table present with that name, then it works fine.**

## Expected/Desired Behavior
Liquibase should be able to distinguish between the tables of different cases.

**Comment by kataggart** [comment]
@aayushi095 confirmed unfortunately this will not be fixed with our current work, so I will move this through our process. thanks!

**Comment by filipelautert** [comment]
This issue has been fixed around Liquibase 4.27.0 . Please reopen if the problem happens again.

**Comment by aayushi095** [comment]
@filipelautert I Tried with 4.27.0 and 5.0.1 versions and still the issue is not resolved. The behavior is same as explained in case1 of description, DatabaseChangeLog.getChangeSets() is still returning null.
Also I do not know why I do not have permissions to reopen this issue.

**Comment by tati-qalified** [comment]
This is still an issue. When having a "demo" table and a "DEMO" table, `liquibase snapshot` joins both outputs as one.
