### ISSUE TITLE
Infinite Loop in ExpressionExpander, if property name same as environment variable

### ISSUE THREAD

**Issue by Thommel** [liquibase/liquibase#2988]
## Environment

**Liquibase Version**: 4.12.0

## Description

ExpressionExpander.java, introduced in 4.12.0 (https://github.com/liquibase/liquibase/pull/2656) results in infinite loop, if property name points to an environment variable with the same name

With 4.11.0, everything works as expected, in 4.12.0, the expander tries to recursively resolve the value of `${DB_NAME}` with the property value of DB_NAME which is again `${DB_NAME}`. However, it should use the environment variable value of DB_NAME (as before)

## Steps To Reproduce

- create a changelog file with property name which points to an environment variable with the same name. E.g.
```
databaseChangeLog:
  - property:
      name: DB_NAME
      value: ${DB_NAME}
```

## Actual Behavior
- Infinite loop resulting in ChangeLogParseException:

```

Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/liquibase/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:86) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:224) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.12.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.20.jar:5.3.20]
	... 63 more
Caused by: java.util.regex.PatternSyntaxException: Stack overflow during pattern compilation
\\
	at java.util.regex.Pattern.error(Pattern.java:2028) ~[?:?]
	at java.util.regex.Pattern.<init>(Pattern.java:1432) ~[?:?]
	at java.util.regex.Pattern.compile(Pattern.java:1069) ~[?:?]
	at java.lang.String.replaceAll(String.java:2942) ~[?:?]
	at liquibase.changelog.DatabaseChangeLog.getLogicalFilePath(DatabaseChangeLog.java:135) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogParameters.getLocalKey(ChangeLogParameters.java:275) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogParameters.getChangelogParameter(ChangeLogParameters.java:249) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.changelog.ChangeLogParameters.getValue(ChangeLogParameters.java:176) ~[liquibase-core-4.12.0.jar:?]
	at liquibase.changelog.ExpressionExpander.expandExpressions(ExpressionExpander.java:44) ~[liquibase-core-4.12.0.jar:?]
```

## Expected/Desired Behavior
Use the value of the environment variable as property of the changelog execution

**Comment by nvoxland** [comment]
It looks like this should be fixed with #2984 as well

**Comment by Thommel** [comment]
@nvoxland Unfortunately, the issue still occurs in v4.13.0. Can you reopen the issue?

**Comment by evgenkolesman** [comment]
This issue is active also in 4.25.1 version
