### ISSUE TITLE
`relativeToChangeLogFile` not working with `SpringResource#resolveSibling`

### ISSUE THREAD

**Issue by kzander91** [liquibase/liquibase#3393]
## Environment

**Liquibase Version**: 4.17

**Liquibase Integration & Version**: Spring Boot 3.0.0-RC1

**Operating System Type & Version**: Windows 10

## Description

Folder structure:
```
src/main/resources/db/changelog/
├── changelog.xml
└── data.csv
```

changelog.xml:
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.5.xsd">

    <changeSet id="relative import" author="kzander91">
        <createTable tableName="my_table">
            <column name="test_col" type="bigint"/>
        </createTable>
        <loadData tableName="my_table"
                  file="data.csv"
                  relativeToChangelogFile="true">
            <column name="test_col" type="bigint"/>
        </loadData>
    </changeSet>

</databaseChangeLog>
```

The `loadData` change resolves `file` to `/data.csv` instead of `/db/data.csv`. This worked previously with 4.9.1 and broke with 4.17.0.
The bug is located in `SpringResource`:
https://github.com/liquibase/liquibase/blob/c9ceb05141eee992c7aaa3002451bb5f531b49d5/liquibase-core/src/main/java/liquibase/integration/spring/SpringResource.java#L40-L49

If `resource` is a `org.springframework.core.io.UrlResource`, `createRelative()` uses `new URL(URL, String)` to resolve the relative URL:
https://github.com/spring-projects/spring-framework/blob/v6.0.0-RC2/spring-core/src/main/java/org/springframework/core/io/UrlResource.java#L310-L317

This effectively calls
```java
new URL(new URL("file://C:/Temp/demo/target/classes/db/changelog/changelog.xml"), "../data.csv")
```
Which resolves to `file://C:/Temp/demo/target/classes/db/data.csv` instead of `file://C:/Temp/demo/target/classes/db/changelog/data.csv`.

## Steps To Reproduce

- Use `<loadData relativeToChangelogFile="true"/>`.
- Start migration with Spring Boot.

## Actual Behavior
Relative file is resolved incorrectly, migration aborts due to "unknown file".

## Expected/Desired Behavior
Relative paths are resolved correctly as before.

## Reproducer
[demo.zip](https://github.com/liquibase/liquibase/files/9838779/demo.zip)

* Unzip and run `mvnw test`, test fails.
* Uncomment `liquibase.version` property in pom and rerun: test succeeds.

## Possibly related
#3354 
#3365 
#3064

**Comment by FBurguer** [comment]
We were able to reproduce this issue, we are adding it to the list of issues to fix. Thanks!

**Comment by konikvranik** [comment]
The path to file is not resolved properly.
My structure is:
```
.
├── database
│   ├── data
│   │   ├── 22.0.0
│   │   │   ├── data.xml
│   │   │   └── migrateUsers.sql
│   └── project_model.xml
```

in `project_model.xml` is `<include file="data/22.0.0/data.xml" relativeToChangelogFile="true" />`, in `data/22.0.0/data.xml` is `<sqlFile path="migrateUsers.sql" relativeToChangelogFile="true"/>`, but liquibase search for the file in `database/data`:
```
Caused by: java.io.FileNotFoundException: JAR entry database/data/migrateUsers.sql not found in fatjar.jar!/BOOT-INF/lib/myapp.jar

```

the behavior started in version 17.0.0. In 16.1.0 it is OK.

**Comment by MalloD12** [comment]
> The path to file is not resolved properly. My structure is:
> 
> ```
> .
> ├── database
> │   ├── data
> │   │   ├── 22.0.0
> │   │   │   ├── data.xml
> │   │   │   └── migrateUsers.sql
> │   └── project_model.xml
> ```
> 
> in `project_model.xml` is `<include file="data/22.0.0/data.xml" relativeToChangelogFile="true" />`, in `data/22.0.0/data.xml` is `<sqlFile path="migrateUsers.sql" relativeToChangelogFile="true"/>`, but liquibase search for the file in `database/data`:
> 
> ```
> Caused by: java.io.FileNotFoundException: JAR entry database/data/migrateUsers.sql not found in fatjar.jar!/BOOT-INF/lib/myapp.jar
> ```
> 
> the behavior started in version 17.0.0. In 16.1.0 it is OK.

Hi @konikvranik,

Thanks for sharing your case. We have already made a code update which should fix this issue, but it is still waiting for review. I hope it can be reviewed soon so we can include it in the next release. 

Thanks,
Daniel.

**Comment by OleksandrShkurat** [comment]
Two days ago there was a tag 4.18.0 created in git repo, however the appropriate artefact is still not released. Why is everything around this issue so slow?

**Comment by XDelphiGrl** [comment]
Hello, @OleksandrShkurat -

The 4.18.0 tag was added when we started our internal release process. Regressions were found which necessitated rework, but the tag in git was not removed during that time. We are still working to get the 4.18.0 release out. There are lots of boring, internal reasons this is the case, but I promise, we're working on it. My apologies for the wait; I too, want to see this released!

-erzsebet (XDelphiGrl)

**Comment by OleksandrShkurat** [comment]
Thank you for the response. By the way, spring-boot 3.0.0 has included buggy 4.17.2 into their first stable release. So, in case of migration to spring-boot 3 it's better to wait for liquibase 4.18.0, or downgrade it to 4.16.1

**Comment by XDelphiGrl** [comment]
You are very welcome. I understand the frustration! Thank you for the information about spring-boot 3.0.0.

**Comment by filipelautert** [comment]
Hey @OleksandrShkurat - 4.18 may be out early next week (we hope so) . Otherwise 4.16.1 should still work fine.

**Comment by XDelphiGrl** [comment]
@OleksandrShkurat, hello! The release went out on Tuesday (6 December, 2022). Thank you for the PR and for being kind about our release delay.

**Comment by OleksandrShkurat** [comment]
Thank you. I already updated my project yesterday
