### ISSUE TITLE
Cannot set ScopeManager when using Maven

### ISSUE THREAD

**Issue by rogierslag** [liquibase/liquibase#4031]
### Search first

- [X] I searched and no similar issues were found

### Description

When building a monorepo, consisting of several (50+) services, Maven will trigger the `generate-sources` phase during which all required files will be generated and written. If the thread count is set to anything higher than 1, the Liquibase plugin will throw more often than not with the following exception:

```
Caused by: java.lang.RuntimeException: Cannot end scope anykuttvkp when currently at scope cqzmxhcleb
    at liquibase.Scope.exit (Scope.java:237)
    at liquibase.Scope.child (Scope.java:198)
    at liquibase.Scope.child (Scope.java:186)
    at liquibase.Scope.child (Scope.java:165)
    at liquibase.Scope.child (Scope.java:256)
    at liquibase.Scope.child (Scope.java:260)
    at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute (AbstractLiquibaseMojo.java:632)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:577)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1589)
```

This seems to be because when the maven plugin is used the SingletonScope seems to be used, whereas for a threadcount of 1+, the newer `ThreadLocalScopeManager` might be a better fix

### Steps To Reproduce

With a project consisting of 50 services, each of which depends on an internal module called `persistence`, and each service shaving a different changelog for different databases, the issue can be triggered running `mvn generate-sources --also-make-dependents --projects libs/persistence -B -e -fae -U -Djava.net.preferIPv4Stack=true -T8`, whereas `mvn generate-sources --also-make-dependents --projects libs/persistence -B -e -fae -U -Djava.net.preferIPv4Stack=true -T1` (note the `-T1`) works flawlessly

### Expected/Desired Behavior

During a multithreaded build, Liquibase should be able to generate sources safely

### Liquibase Version

4.20.0

### Database Vendor & Version

Postgresql 13.9

### Liquibase Integration

maven

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by rogierslag** [comment]
Refs https://github.com/liquibase/liquibase/issues/3554 https://github.com/liquibase/liquibase/issues/2248

**Comment by trico-tillster** [comment]
I am still seeing this issue with 4.23, build fails using a single thread maven run.
`Error:  Failed to execute goal org.liquibase:liquibase-maven-plugin:4.23.0:update (liquibase) on project ordering-db-schema: Cannot end scope ztupxdjtqp when currently at scope root`

Have I miss something to solve this scope problem? Thank you

**Comment by caminaman741** [comment]
Hi @trico-tillster, did you find what is the issue. I am also facing the similar issue. I made the following change -
`Scope.setScopeManager(new ThreadLocalScopeManager());`
Now I am getting the issue that says "when currently at scope root" instead of "when currently at scope xyz"

**Comment by filipelautert** [comment]
@trico-tillster @caminaman741 we added some more threading fixes to 4.24.0 , hopefully it fixes it for you.

**Comment by filipelautert** [comment]
Hello @rogierslag ! We just released Liquibase 4.25.1 yesterday with moire scope fixes, do you mind giving it a try?

**Comment by jaroslav-sagan-evooq** [comment]
Hi @filipelautert, I have just tested `Liquibase 4.25.1` and I'm still getting the scope error

**Comment by rogierslag** [comment]
Not getting this specific scope error, but it incidentally fails with 

```
ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "databasechangeloglock" does not exist
[ERROR]   Position: 8
```

**Comment by filipelautert** [comment]
@rogierslag that's a different one.. We are working on this one too under https://github.com/liquibase/liquibase/issues/5034 and https://github.com/liquibase/liquibase/issues/4708

**Comment by CG49071** [comment]
Hi Team, I am also facing Scope issue with Multithreading. https://github.com/liquibase/liquibase/issues/5426 - Can anyone please help on this

**Comment by rogierslag** [comment]
> @rogierslag that's a different one.. We are working on this one too under #5034 and #4708 

I can no longer reproduce the scope issue at least
