### ISSUE TITLE
MySQL generateChangeLog generates ENUM types incorrectly as ENUM with a numerical precision

### ISSUE THREAD

**Issue by OisinWard** [liquibase/liquibase#4142]
### Search first

- [X] I searched and no similar issues were found

### Description

I found this bug in the liquibase forms 10 years ago and was said to be resolved so this is possibly a regression: https://forum.liquibase.org/t/generatechangelog-does-not-work-with-enum/2772

When using generateChangelog for a MySQL database the MySQL enum datatype is incorrectly generated as enum(7) or other precision this causes an error if you try to update with that value as it is invalid for MySQL.

mysql server version 5.7.41
liquibase version: 4.20.0

This is a follow on from a forum post I created: https://forum.liquibase.org/t/liquibase-generate-changelog-doesnt-work-with-mysql/8059

This also occurs with a mariadb configured liquibase client on a MySQL server.

### Steps To Reproduce

Create the following table

```
CREATE TABLE `liquibase_example_table` (
    id INT(11) NOT NULL AUTO_INCREMENT,
    enum_column ENUM('option1', 'option2', 'option3') NOT NULL,
    json_column JSON NOT NULL,
    text_column TEXT NOT NULL,
    INDEX text_column_idx (text_column(100)),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Run create changelog and the output will have the incorrect datatype.

```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM(7) NOT NULL, json_column JSON(1073741824) NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column);
```

### Expected/Desired Behavior

The generatedChangelog should be similar to the original create statement so:

```
-- liquibase formatted sql

-- changeset root:1681305995631-1
CREATE TABLE liquibase_example_table (id INT AUTO_INCREMENT NOT NULL, enum_column ENUM('option1', 'option2', 'option3') NOT NULL, json_column JSON NOT NULL, text_column TEXT NOT NULL, CONSTRAINT PK_LIQUIBASE_EXAMPLE_TABLE PRIMARY KEY (id));

-- changeset root:1681305995631-2
CREATE INDEX text_column_idx ON liquibase_example_table(text_column(100));
```

### Liquibase Version

liquibase version: 4.20.0

### Database Vendor & Version

MySQL server version 5.7.41

### Liquibase Integration

CLI

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Ubuntu 20.04

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by OisinWard** [comment]
I found this problem occurs when using a SQL changelog. It does not occur with xml changelog.

**Comment by nwcm** [comment]
@OisinWard this should be resolved as per https://github.com/liquibase/liquibase/pull/3842

**Comment by OisinWard** [comment]
This is not fixed when using generate changelog for a sql type changelog. It is fixed for an xml type changelog. Still an issue.
