### ISSUE TITLE
MultiTenantSpringLiquibase uses incorrect/default schema when processing createView change type

### ISSUE THREAD

**Issue by nealeduncan1** [liquibase/liquibase#4316]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a multi-tenant application with a database. The database has separate schemas per tenant and is managed by Liquibase integration with Spring Boot.

By configuring the MultiTenantSpringLiquibase bean I am able to successfully process my Liquibase change sets upon starting my application for the most part - however when using `createView` changetypes, the wrong schema (default) is used in the body of the view for table names (and joins)

### Steps To Reproduce

Changelog:
```
  <changeSet id="1" author="x" runOnChange="true">
    <createView
      path="views/vw_get_status.sql"
      relativeToChangelogFile="true"
      replaceIfExists="true"
      viewName="vw_get_status"/>
  </changeSet>
```

vw_get_status.sql:
```
SELECT id,
       name,
FROM status
```

What is actually deployed in tenant1:
```
create or replace view `tenant1`.`vw_get_status` as
select
    `defaultSchema`.`status`.`id` as `id`,
    `defaultSchema`.`status`.`name` as `name`,
from
    `defaultSchema`.`status`
```

What is actually deployed in tenant2:
```
create or replace view `tenant2`.`vw_get_status` as
select
    `defaultSchema`.`status`.`id` as `id`,
    `defaultSchema`.`status`.`name` as `name`,
from
    `defaultSchema`.`status`
```

The defaultSchema above is inserted by liquibase meaning that the incorrect schema is in the body of the view

### Expected/Desired Behavior

The correct / current schema (i.e. tenant1) should be in the body of the view for table names

### Liquibase Version

4.21.0

### Database Vendor & Version

Mysql 8

### Liquibase Integration

Spring Boot 2.7.3

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment]
This is maybe the same cause as #4324 ?

**Comment by filipelautert** [comment]
Hello @nealeduncan1 ! By your descriptions it seems to be the same problem that was fixed on  https://github.com/liquibase/liquibase/pull/4427 that is already merged to master for the next release.
I'll close the issue as fixed by that PR , feel free to test master build and reopen it if the issue still persists.

**Comment by nealeduncan1** [comment]
Just tried with 4.23.1 - this is still an issue and not fixed. - can it be re-opened please?

**Comment by nealeduncan1** [comment]
Just tried with 4.23.1 - this is still an issue and not fixed.
