### ISSUE TITLE
MultiTenantSpringLiquibase only creates procedures in the default schema

### ISSUE THREAD

**Issue by nealeduncan1** [liquibase/liquibase#4324]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a multi-tenant application with a database. The database has separate schemas per tenant and is managed by Liquibase integration with Spring Boot.

By configuring the MultiTenantSpringLiquibase bean I am able to successfully process my Liquibase change sets upon starting my application for the most part - however when using createProcedured changetypes, the procedure is only created in the default schema, and none of the other tenant databases.

### Steps To Reproduce

Changelog:

```
  <changeSet id="999" author="xyz" runOnChange="true">
    <createProcedure
      path="procedures/sp_get_data.sql"
      relativeToChangelogFile="true"
      replaceIfExists="true"
      procedureName="sp_get_data"/>
  </changeSet>
```

The procedure sp_get_data is only deployed to the default schema, and no other tenant databases.  An entry is made in the databasechangelog table for it in each database.

### Expected/Desired Behavior

The procedured sp_get_data should be deployed to each tenant database, not just the default.

### Liquibase Version

4.21.0

### Database Vendor & Version

Mysql 8

### Liquibase Integration

Spring Boot 2.7.3

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by troligsownder** [comment]
This is the same issue as reported in https://github.com/liquibase/liquibase/issues/4304. I debugged this issues and wrote my findings in that issue report.

**Comment by nvoxland** [comment]
Thanks, @troligsownder! Would you be up for submitting a PR to fix it?

**Comment by filipelautert** [comment]
Hello @nealeduncan1 ! As @troligsownder noticed this is the same issue as https://github.com/liquibase/liquibase/issues/4304 and has been fixed on https://github.com/liquibase/liquibase/pull/4427 that is already merged to master for the next release.

**Comment by nealeduncan1** [comment]
Just tried with 4.23.1 - this is still and issue and not fixed.

**Comment by filipelautert** [comment]
Hello @nealeduncan1 - just to make sure: the problem only happens with `createProcedure` change type for you? For other changes like "`createTable`" it works fine right?

**Comment by nealeduncan1** [comment]
Hi @filipelautert, yes I have only seen this with `createProcedure` -  `createTable` works fine.  There is another related issue however, the `createView` has an issue with defaultSchema in the body of the view #4316

**Comment by filipelautert** [comment]
@tati-qalified could you try to reproduce this issue? thanks
