### ISSUE TITLE
Liquibase website is unavailable

### ISSUE THREAD

**Issue by jonjomckay** [liquibase/liquibase#4355]
### Search first

- [X] I searched and no similar issues were found

### Description

As of this morning UK time, the [liquibase.org](https://liquibase.org) website is unavailable.

Over HTTPS, I get a certificate mismatch error (the cert is for `*.wpengine.com, wpengine.com`). Over HTTP, I get a "Site is not available" message from WP Engine.

This is unfortunately now blocking our database migrations, as the XML parser is trying to download the XSD from liquibase.org.

### Steps To Reproduce

Visit [liquibase.org](https://liquibase.org) in a web browser.

### Expected/Desired Behavior

The [liquibase.org](https://liquibase.org) website loads successfully, with a valid TLS certificate, and database migrations are able to be executed successfully.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by SasRei** [comment]
Same here 👀

**Comment by matsta25** [comment]
Just remove `s` from `https`.

**Comment by davillafer** [comment]
😭😭😭

**Comment by alexgutnik** [comment]
same thing, that needs to be fixed

**Comment by mauritsdebruin** [comment]
panic do fix

**Comment by palmtopicus** [comment]
my production is down thx

**Comment by lennart683** [comment]
Same here 👀

**Comment by NetruN** [comment]
I tried to contact wpengine via chat and mail. They only respond to the website owner if contacted via their portal.

**Comment by aozmen121** [comment]
@nvoxland or @wwillard7800  Can you please help, our production deployments are failing due to XSD dns paths is no longer valid:
http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd

**Comment by ojas-krishnaprasad** [comment]
Same here :eyes:

**Comment by shivangivar** [comment]
Same here Is there any workaround ? How can we contact the support ?

**Comment by aashgr** [comment]
Same here ^_^

**Comment by LyubinskiyPavel** [comment]
You can upgrade your dependency version (i have upgraded upto 4.16.0). it help me. There are schemas in artifact

**Comment by shivangivar** [comment]
> de your dependency version (i have upgraded upto 4.16.0). it help me. There are schemas in artifact
Hey can you tell me how you have used it cause when i upgrade my version it couldn't find my property file . It was able to find the path earlier of my property file can you tell me the plugin configuration in pom.xml

**Comment by shivangivar** [comment]
> You can upgrade your dependency version (i have upgraded upto 4.16.0). it help me. There are schemas in artifact

Hey can you tell me how you have used it cause when i upgrade my version it couldn't find my property file . It was able to find the path earlier of my property file can you tell me the plugin configuration in pom.xml

**Comment by shivangivar** [comment]
> 

@jonasvoelcker 
Hey how can i change the schemalocation to local directory ?

**Comment by kevin-atx** [comment]
The liquibase.org site is back up and the XSDs should be available again. Could you let us know if things are working for you again?

**Comment by jonasvoelcker** [comment]
It doesn't work :/

**Comment by NetruN** [comment]
I can confirm that it works. Use a browser with private or incognito mode or a browser that you have not opened the website today.

**Comment by ingokuba** [comment]
> The liquibase.org site is back up and the XSDs should be available. Could you let us know if things are working for you again?

Still getting an error for `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd` because of the 301 return code - should switch to `https` it seems :smiling_face_with_tear:

**Comment by blangley88** [comment]
> The liquibase.org site is back up and the XSDs should be available. Could you let us know if things are working for you again?

I can curl the XSD from the command line but our web application is returning a 403 error when attempting to fetch the XSD. I believe this might be due to the cert change and our previously signed cert in the java keystore not aligning with the new certificate issued to the site.

**Comment by kevin-atx** [comment]
Yes - you will need to use `https` instead of `http`.

**Comment by aozmen121** [comment]
Issue continues to be perceived with 301 redirect errors:
![image](https://github.com/liquibase/liquibase/assets/60323377/acdf0291-5e5f-4ca4-9510-05ed5127380f)

**Comment by jonjomckay** [comment]
It looks like the website is now up and accessible, but there seems to now be a redirect in place from HTTP to HTTPS, which breaks older versions of Liquibase. Can the redirect be reverted? We have old versions in the wild that we can't (easily) update, and they're now broken.

```
liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Error parsing line 2 column 35 of liquibase-boomi-bus.xml: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:216)
        at liquibase.Liquibase.update(Liquibase.java:189)
        at liquibase.Liquibase.update(Liquibase.java:178)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1639)
        at liquibase.integration.commandline.Main.run(Main.java:303)
        at liquibase.integration.commandline.Main.main(Main.java:159)
```

**Comment by ingokuba** [comment]
Fun fact: Even with HTTPS enabled I'm getting an error - it sounds like the XSD itself has changed? :thinking: 

```
liquibase.exception.ChangeLogParseException: Error parsing line 3 column 137 of META-INF/changelog.xml: cvc-elt.1.a: Cannot find the declaration of element 'databaseChangeLog'
```

I'll investigate further - maybe my fault

**Comment by dvt-blip-ui** [comment]
> Fun fact: Even with HTTPS enabled I'm getting an error - it sounds like the XSD itself has changed? 🤔
> 
> ```
> liquibase.exception.ChangeLogParseException: Error parsing line 3 column 137 of META-INF/changelog.xml: cvc-elt.1.a: Cannot find the declaration of element 'databaseChangeLog'
> at org.liquibase//liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:113)
> 	at org.liquibase//liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
> 	at org.liquibase//liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
> 	at org.liquibase//liquibase.Liquibase$16.run(Liquibase.java:1982)
> 	at org.liquibase//liquibase.Scope.lambda$child$0(Scope.java:180)
> 	at org.liquibase//liquibase.Scope.child(Scope.java:189)
> 	at org.liquibase//liquibase.Scope.child(Scope.java:179)
> 	at org.liquibase//liquibase.Scope.child(Scope.java:158)
> 	at org.liquibase//liquibase.Liquibase.runInScope(Liquibase.java:2405)
> 	at org.liquibase//liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1978)
> ```
> 
> I'll investigate further - maybe my fault
> 
> edit: ℹ️ Using liquibase-core 4.8.0

Hi, have you added https only to this link? :  https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd

I say this because I got your error if I add https to the xmlns properties urls of the databasechangelog element.

Only this url : https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, others with http its okey for me.

regards!

**Comment by kevin-atx** [comment]
We're looking into the `http `to `https` redirect with the goal of removing the redirect. I'll share an update with you when I hear back.

**Comment by ojas-krishnaprasad** [comment]
@kevin-atx We are getting 403 errors either with http / https as well
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1902)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1500)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:268)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity (XMLEntityManager.java:648)
    at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion (XMLVersionDetector.java:148)
    at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse (SchemaParsingConfig.java:582)

**Comment by ingokuba** [comment]
Thank you @dvt-blip-ui :pray: 

**Only** updating the link to the changeog xsd seems to be the solution:

```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog 
                      https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
```
(line breaks for readability)

**Comment by kevin-atx** [comment]
I just heard from the team that the automatic XSD redirect from `http` to `https` has been removed. Caching might still be an issue for people (clearing the cache or time should address that). Please let me know if this change helps the situation for those that still have trouble accessing the XSDs.

**Comment by TheHandOfNOD** [comment]
another way to avoid this problem also in future is to switch to a YAML definition

**Comment by jigacristina** [comment]
Hi everyone! Does anyone know if we have any ETA for resolving this issue?

**Comment by jnewton03** [comment]
Hi All,  this issue has been resolved, but you may need to clear your browser cache.  To confirm, do the following:

1. Open a private browsing window
2. Open developer tools -> network
3. Navigate to your desired XSD using http
4. You should see a 200 OK instead of a 301 Redirect

Example: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd

**Comment by kjthorpe18** [comment]
I can retrieve XSD files with the browser, but builds in my CI pipeline using the liquibase-maven-plugin are failing on a year old changeset - the error still occurs:
```
Failed to read schema document 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.: Server returned HTTP response code: 403 for URL: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd -> [Help 1]
```

**Comment by ojas-krishnaprasad** [comment]
@jnewton03  You can use this https://github.com/ojas-krishnaprasad/Liquibase, **mvn liquibase:update**

**Comment by jonasvoelcker** [comment]
For us this worked:

```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">
```

**Comment by jnewton03** [comment]
@ojas-krishnaprasad  thank you SO MUCH.  Very helpful.  I worked with support at our hosting provider and tweaked the redirects to *not* require HTTPS for anything after www.liquibase.org/xml/

We were able to successfully run your project now.  We also tried updating the `maven-compiler-plugin` and `liquibase-maven-plugin` to the latest available versions and that was also successful.

Can you all try your projects again and let me know if it's still failing?

**Comment by azfdgdasfgdagf** [comment]
Still failing, a 403 error on the URL  https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd

**Comment by jnewton03** [comment]
> Still failing, a 403 error on the URL https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd

Hi!  I updated the changelog in the sample project @ojas-krishnaprasad provided and it was successful:
```
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
```

Would you mind sharing a sample changelog that fails for you?

**Comment by nvoxland** [comment]
> Still failing, a 403 error on the URL https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd

@azfdgdasfgdagf what Liquibase version are you using?

**Comment by azfdgdasfgdagf** [comment]
This is with liquibase 3.4.1, the header in a changelog that fails seems identical to yours.  It's maven building a jar.

<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
		xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">

	<include file="indexing_schema_1.0.xml" relativeToChangelogFile="true"/>

</databaseChangeLog>

full error is 

[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:updateSQL (Generate SQL Server Schema) on project ovitas-indexing: Error setting up or running Liquibase: Error parsing line 4 column 133 of C:/(path removed)/master.changelog.xml: schema_reference.4: Failed to read schema document 'https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd -> [Help 1]

**Comment by nvoxland** [comment]
Thanks, @azfdgdasfgdagf . Since you are on 3.4.x, you'll need to keep your XSD version as 3.4.xsd or lower. 

We'll see about what is causing 3.4.1 to get the 403 error, but the reason it's going out to the network in the first place is becuase 3.5 is not packaged in your version of liquibase (because it didn't exist when 3.4.1 was released). So even when we do fix the network issue, it's still setting you up for problems where the XSD is suggesting that some XML attributes are valid when they were not actually valid in 3.4.1.

By going to the 3.4.xsd, Liquibase will find it packaged in the application and use that without having to go out to the network and hit the 403 error.

**Comment by kjthorpe18** [comment]
I'm still seeing the same error using `liquibase-maven-plugin` `v. 3.4.1`. Changing to `https` still results in the same error. Heres the changelog:

```xml
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xmlns:pro="http://www.liquibase.org/xml/ns/pro"
        xsi:schemaLocation="
          http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
          http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
          http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">
```
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.018 s
[INFO] Finished at: 2023-06-06T20:53:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:update (default) on project end-user-sync-db: Error setting up or running Liquibase: liquibase.exception.SetupException: Error parsing line 11 column 70 of db/changelogs/my_changelog.xml: schema_reference.4: Failed to read schema document 'https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd -> [Help 1]
```

**Comment by ojas-krishnaprasad** [comment]
> 

What changes you made it to work. Still i am facing same issue

**Comment by ojas-krishnaprasad** [comment]
> @ojas-krishnaprasad thank you SO MUCH. Very helpful. I worked with support at our hosting provider and tweaked the redirects to _not_ require HTTPS for anything after [www.liquibase.org/xml/](http://www.liquibase.org/xml/)
> 
> We were able to successfully run your project now. We also tried updating the `maven-compiler-plugin` and `liquibase-maven-plugin` to the latest available versions and that was also successful.
> 
> Can you all try your projects again and let me know if it's still failing?

What changes you made it to work. Still i am facing same issue

**Comment by nvoxland** [comment]
@kjthorpe18 If you are on 3.4.1, the `-latest.xsd` won't work for you. The overall logic liquibase should be doing is:
1) If the referenced xsd can be found bundled with the liquibase build, use that
2) If not, try to download it (this is normally not what you want anyway, and later versions of liquibase disable this from even being tried by default)

Step 2 is having a problem on our server we're looking into, but you should be able to stop it at step 1 by only referencing xsd filese that are bundled in your version of Liquibase. So for 3.4.1, that will be `dbchangelog-3.4.xsd` or earlier. The `dbchangelog-latest.xsd` file was only introduced around 4.12, so if you are on any versions before 4.12 then requesting dbchangelog-latest.xsd will still be trying to go out to the network.

If you change your reference to `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd` does it work?

Also: if you are have a reference to a liquibase-pro xsd file with 3.4.1 you'll also be hitting the "fall back to the network" step, since there was no support for any pro functionality in 3.4.1. Removing that xsd reference will help too.

**Comment by petru1988** [comment]
Found on another [forum](https://forum.liquibase.org/t/403-forbidden-on-schema-dbchangelog-3-4-xsd-from-circleci-com/4117) and was able to reproduce the issue in Postman. 
1. Create a `GET` request to `https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd` and execute. We content of XSD is returned and status is 200.
2. Add `User-Agent: Java/1.8.0_251` request header. Now the response is 403 and I can see an error message:
```
Error 1010
Ray ID: 7d36b3e76dca9555 • 2023-06-07 06:05:19 UTC
Access denied
What happened?
The owner of this website (www.liquibase.org) has banned your access based on your browser's signature (7d36b3e76dca9555-ua21).
```

**Comment by marbetschar** [comment]
same here, how getting the following exception:

```shell
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:582)
	...
```

**Comment by MarcusNye75** [comment]
same here getting 403 when we use liquibase in a maven build.  Last time this happened back in 2022 it wass due to something rejecting the java in the user-agent (we can access via the browser fine).  Guessing when everything has came back up certain settings (user-agent permissions) have not been re-applied.

**Comment by petru1988** [comment]
We're using liquibase v 3.* and the solution was to switch from `https` to `http`. This will use XSD files bundled in liquibase library. 
https://github.com/liquibase/liquibase/blob/3.3.x/liquibase-core/src/main/java/liquibase/parser/core/xml/StandardNamespaceDetails.java

**Comment by ptpu** [comment]
Hey, same error here using Azure App Services to run my application:

```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902) ~[?:1.8.0_345]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500) ~[?:1.8.0_345]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_345]
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source) ~[xercesImpl-2.12.0.jar:2.12.0]
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source) ~[xercesImpl-2.12.0.jar:2.12.0]
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.impl.xs.opti.SchemaDOMParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
```

On my local environment I can download the xsd

**Comment by sviluppopg** [comment]
Hi, same error here.

`
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
....
`

Error Log:
`
{"log":":: JHipster    :: Running Spring Boot 1.4.1.RELEASE ::\n","stream":"stdout","time":"2023-06-07T08:30:03.746367277Z"}
...
{"log":"2023-06-07 10:30:17.330  WARN 7 --- [           main] liquibase                                : schema_reference.4: lettura del documento di schema \"http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd\" non riuscita perché 1) non è stato possibile trovare il documento; 2) non è stato possibile leggere il documento; 3) l'elemento radice del documento non è \u003cxsd:schema\u003e.\n","stream":"stdout","time":"2023-06-07T08:30:17.330899683Z"}
`

**Comment by ptpu** [comment]
I think the error is that Cloudflare restrict access with e.g. User-Agent: Java/1.8.0_251

**Comment by ptpu** [comment]
https://forum.liquibase.org/t/tomcat-not-starting-getting-403-error-from-liquibase/8311

Here is the ungoing discussion on forum.liquibase.org

**Comment by jnewton03** [comment]
Thanks all.  Great find.  Working with WPEngine support right now and will post an update shortly.

**Comment by MatthewSBarnes** [comment]
Flow that wasn't working for me previously is now successful. Thank you!

**Comment by azfdgdasfgdagf** [comment]
It is fixed for me also

**Comment by kjthorpe18** [comment]
Changing the xsd to a version specific (dbchangelog-3.4.xsd) one worked for me, thanks!

**Comment by sviluppopg** [comment]
Now everything works! Thank you!!

**Comment by jnewton03** [comment]
OK, so now everything should be back up and running.  Here's what happened:
* liquibase.org is hosted on WPEngine on their legacy network.
* Yesterday (6/6) there was an outage with our site
* The solution from WPEngine was to update our DNS to use their Advanced Network Offering
* This brought the site back online, but broke HTTP redirects for XSDs and enabled CloudFlare security which blocks Java agents < version 10.
* Today we reverted the DNS change back to the legacy network.  I've tested access to the XSDs via browser, curl, and liqubase-maven-plugin and all seem to be working.

Thank you all for being patient with us.  Apologies for the outage.  We are looking at ways to mitigate this type of thing in the future.

**Comment by jnewton03** [comment]
Closing this issue, but feel free to re-open if ya'll see more problems.

**Comment by sheik61** [comment]
Hi team,

It appears the issue reported in this thread has resurfaced. As of today, we are still encountering errors related to certificate mismatches and unavailable XSD schemas, which are blocking our database migrations. The issue persists despite clearing cache, switching browsers, and upgrading Liquibase versions.

Could this issue be reopened for further investigation?

Thanks for your attention to this matter.

**Comment by ptpu** [comment]
Same here...

**Comment by thangnq1001** [comment]
You guys can try https://github.com/liquibase/liquibase/issues/6364#issuecomment-2376625135, worked for me.

**Comment by jnewton03** [comment]
@sheik61 @ptpu @thangnq1001 This was, indeed, a DNS issue.  It has since been resolved.  Please reply if you are still having issues.
