### ISSUE TITLE
Breaking changes introduced in 4.17.0 : filename calculated is different after 4.17.0 version

### ISSUE THREAD

**Issue by SabeetaBhandari** [liquibase/liquibase#5607]
### Search first

- [X] I searched and no similar issues were found

### Description

We have stumbled onto this while upgrading to spring boot 3.1.6 from 2.7.18

Existing changelogs that have already been run is getting picked up to be executed by liquibase after version 4.17.0.

The underlying issue is the filename calculated for the same changesets is different in liquibase 4.17.0(and later) from 4.16.1.

Here is the stack trace :

`Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/chnge1/change2/0001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:291) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:290) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2447) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:236) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:221) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328) ~[liquibase-core-4.17.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283) ~[liquibase-core-4.17.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
	... 18 common frames omitted`

### Steps To Reproduce

Here is the changelogs:

master-changelog.xml in directory liquibase/changelogs
`<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    <include file="classpath*:liquibase/changelogs/chnge1/master-changelog-1.xml"/>
</databaseChangeLog>`

master-changelog-1.xml in directory liquibase/changelogs/chnge1
`<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    <include file="change2/0001-initial.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>`

0001-initial.xml in directory liquibase/changelogs/chnge1/change2
`<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                            http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
    <changeSet author="test_liquibase_sabeeta" id="1">
        <createTable tableName="company">
            <column name="id" type="int">
                <constraints primaryKey="true" nullable="false"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
`

This changelog ran with liquibase version 4.16.1 (<4.17.0) creates the databasechangelog entry with filename as "classpath*:liquibase/changelogs/chnge1/change2/0001-initial.xml"

The same thing running at 4.17.0 or later fails with error "company table already exists". This is because after 4.17.0 The same changeset has filename evaluated as "liquibase/changelogs/chnge1/change2/0001-initial.xml". The filename doesn't match with the entry in databasechangelog table (created with liquibase version<4.17.0), therefore tries to run the same changeset and fails.
[test-liquibase 2.zip](https://github.com/liquibase/liquibase/files/14341372/test-liquibase.2.zip)

Here is the reproducer code, Please run the TestLiquibaseApplicaion with following args :
`-Dspring.datasource.url=jdbc:postgresql://localhost:5432/testing
-Dspring.datasource.username=postgres
-Dspring.datasource.password=password
-Dspring.liquibase.change-log=classpath:liquibase/changelogs/master-changelog.xml`

**IMPORTANT :**
In master-changelog.xml in directory liquibase/changelogs, notice the file field containing "classpath*:" in the  :

1. With file="classpath*:liquibase/changelogs/chnge1/master-changelog-1.xml" : The filename before 4.17.0 is "classpath*:liquibase/changelogs/chnge1/change2/0001-initial.xml" and after 4.17.0 is "liquibase/changelogs/chnge1/change2/0001-initial.xml". Therefore, migration issue happens.

3. With file="liquibase/changelogs/chnge1/master-changelog-1.xml" : The filename of changeset is same before and after 4.17.0 liquibase ie "liquibase/changelogs/chnge1/change2/0001-initial.xml". Therefore no migration issue.

### Expected/Desired Behavior

The calculated filename should never change in liquibase upgrades as this forms the unique identifier for changesets.

### Liquibase Version

4.17.0

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by SabeetaBhandari** [comment]
I believe this isthe change that is causing this issue : https://github.com/liquibase/liquibase/pull/3064

**Comment by tati-qalified** [comment]
Hi @SabeetaBhandari, we were aware of this problem, and it's fixed by versions 4.25 and onwards. Could you try updating your Liquibase version and re-running your program?

Let me know whether it works for you or not.
Thank you,
Tatiana

**Comment by SabeetaBhandari** [comment]
Hi @tati-qalified , 

I can still see the same issue with 4.25.0, 4.25.1, 4.26.0

The existing changeset is running again due to different filename generated for the same changeset:

Here's the stack trace for this :

```
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/testing -Dspring.datasource.username=postgres -Dspring.datasource.password=password -Dspring.liquibase.change-log=classpath:liquibase/changelogs/master-changelog.xml -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dmanagement.endpoints.jmx.exposure.include=* -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=49859:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/bsabeeta/Documents/Work/LearningProjects/test-liquibase 2/target/classes:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter/3.1.8/spring-boot-starter-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot/3.1.8/spring-boot-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-context/6.0.16/spring-context-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.1.8/spring-boot-autoconfigure-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.1.8/spring-boot-starter-logging-3.1.8.jar:/Users/bsabeeta/.m2/repository/ch/qos/logback/logback-classic/1.4.14/logback-classic-1.4.14.jar:/Users/bsabeeta/.m2/repository/ch/qos/logback/logback-core/1.4.14/logback-core-1.4.14.jar:/Users/bsabeeta/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.20.0/log4j-to-slf4j-2.20.0.jar:/Users/bsabeeta/.m2/repository/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar:/Users/bsabeeta/.m2/repository/org/slf4j/jul-to-slf4j/2.0.11/jul-to-slf4j-2.0.11.jar:/Users/bsabeeta/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-core/6.0.16/spring-core-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-jcl/6.0.16/spring-jcl-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/3.1.8/spring-boot-starter-data-jpa-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-aop/3.1.8/spring-boot-starter-aop-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-aop/6.0.16/spring-aop-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/aspectj/aspectjweaver/1.9.21/aspectjweaver-1.9.21.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/3.1.8/spring-boot-starter-jdbc-3.1.8.jar:/Users/bsabeeta/.m2/repository/com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-jdbc/6.0.16/spring-jdbc-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/hibernate/orm/hibernate-core/6.2.20.Final/hibernate-core-6.2.20.Final.jar:/Users/bsabeeta/.m2/repository/jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar:/Users/bsabeeta/.m2/repository/jakarta/transaction/jakarta.transaction-api/2.0.1/jakarta.transaction-api-2.0.1.jar:/Users/bsabeeta/.m2/repository/org/jboss/logging/jboss-logging/3.5.3.Final/jboss-logging-3.5.3.Final.jar:/Users/bsabeeta/.m2/repository/org/hibernate/common/hibernate-commons-annotations/6.0.6.Final/hibernate-commons-annotations-6.0.6.Final.jar:/Users/bsabeeta/.m2/repository/io/smallrye/jandex/3.0.5/jandex-3.0.5.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/bsabeeta/.m2/repository/net/bytebuddy/byte-buddy/1.14.11/byte-buddy-1.14.11.jar:/Users/bsabeeta/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.4/jaxb-runtime-4.0.4.jar:/Users/bsabeeta/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.4/jaxb-core-4.0.4.jar:/Users/bsabeeta/.m2/repository/org/eclipse/angus/angus-activation/2.0.1/angus-activation-2.0.1.jar:/Users/bsabeeta/.m2/repository/org/glassfish/jaxb/txw2/4.0.4/txw2-4.0.4.jar:/Users/bsabeeta/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar:/Users/bsabeeta/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar:/Users/bsabeeta/.m2/repository/org/antlr/antlr4-runtime/4.10.1/antlr4-runtime-4.10.1.jar:/Users/bsabeeta/.m2/repository/org/springframework/data/spring-data-jpa/3.1.8/spring-data-jpa-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/data/spring-data-commons/3.1.8/spring-data-commons-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-orm/6.0.16/spring-orm-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-tx/6.0.16/spring-tx-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-beans/6.0.16/spring-beans-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/slf4j/slf4j-api/2.0.11/slf4j-api-2.0.11.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-aspects/6.0.16/spring-aspects-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar:/Users/bsabeeta/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.1.8/spring-boot-starter-web-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.1.8/spring-boot-starter-json-3.1.8.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.3/jackson-databind-2.15.3.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.3/jackson-annotations-2.15.3.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.3/jackson-core-2.15.3.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.15.3/jackson-datatype-jdk8-2.15.3.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.15.3/jackson-datatype-jsr310-2.15.3.jar:/Users/bsabeeta/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.15.3/jackson-module-parameter-names-2.15.3.jar:/Users/bsabeeta/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.1.8/spring-boot-starter-tomcat-3.1.8.jar:/Users/bsabeeta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.18/tomcat-embed-core-10.1.18.jar:/Users/bsabeeta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.18/tomcat-embed-el-10.1.18.jar:/Users/bsabeeta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.18/tomcat-embed-websocket-10.1.18.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-web/6.0.16/spring-web-6.0.16.jar:/Users/bsabeeta/.m2/repository/io/micrometer/micrometer-observation/1.11.8/micrometer-observation-1.11.8.jar:/Users/bsabeeta/.m2/repository/io/micrometer/micrometer-commons/1.11.8/micrometer-commons-1.11.8.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-webmvc/6.0.16/spring-webmvc-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/springframework/spring-expression/6.0.16/spring-expression-6.0.16.jar:/Users/bsabeeta/.m2/repository/org/liquibase/liquibase-core/4.26.0/liquibase-core-4.26.0.jar:/Users/bsabeeta/.m2/repository/com/opencsv/opencsv/5.9/opencsv-5.9.jar:/Users/bsabeeta/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/bsabeeta/.m2/repository/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.jar:/Users/bsabeeta/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/Users/bsabeeta/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar:/Users/bsabeeta/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.1/jakarta.xml.bind-api-4.0.1.jar:/Users/bsabeeta/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.2/jakarta.activation-api-2.1.2.jar com.example.testliquibase.TestLiquibaseApplication
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/Users/bsabeeta/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=jks

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.8)

2024-03-22T10:18:59.371+05:30  INFO 8509 --- [           main] c.e.t.TestLiquibaseApplication           : Starting TestLiquibaseApplication using Java 17.0.9 with PID 8509 (/Users/bsabeeta/Documents/Work/LearningProjects/test-liquibase 2/target/classes started by bsabeeta in /Users/bsabeeta/Documents/Work/LearningProjects/test-liquibase 2)
2024-03-22T10:18:59.378+05:30  INFO 8509 --- [           main] c.e.t.TestLiquibaseApplication           : No active profile set, falling back to 1 default profile: "default"
2024-03-22T10:18:59.850+05:30  INFO 8509 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-03-22T10:18:59.865+05:30  INFO 8509 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9 ms. Found 0 JPA repository interfaces.
2024-03-22T10:19:00.276+05:30  INFO 8509 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2024-03-22T10:19:00.284+05:30  INFO 8509 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-22T10:19:00.284+05:30  INFO 8509 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-22T10:19:00.373+05:30  INFO 8509 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-22T10:19:00.373+05:30  INFO 8509 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 958 ms
2024-03-22T10:19:00.480+05:30  INFO 8509 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-03-22T10:19:00.633+05:30  INFO 8509 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@759de304
2024-03-22T10:19:00.634+05:30  INFO 8509 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-03-22T10:19:00.743+05:30  INFO 8509 --- [           main] liquibase.database                       : Set default schema name to public
2024-03-22T10:19:01.169+05:30  INFO 8509 --- [           main] liquibase.changelog                      : Reading from public.databasechangelog
2024-03-22T10:19:01.253+05:30  INFO 8509 --- [           main] liquibase.lockservice                    : Successfully acquired change log lock
2024-03-22T10:19:01.255+05:30  INFO 8509 --- [           main] liquibase.command                        : Using deploymentId: 1082941255
2024-03-22T10:19:01.259+05:30  INFO 8509 --- [           main] liquibase.changelog                      : Reading from public.databasechangelog
2024-03-22T10:19:01.270+05:30  INFO 8509 --- [           main] liquibase.ui                             : Running Changeset: liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta
2024-03-22T10:19:01.282+05:30 ERROR 8509 --- [           main] liquibase.changelog                      : ChangeSet liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta encountered an exception.

liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:252) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:256) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.CommandScope.execute(CommandScope.java:217) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:1419) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:234) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:212) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:343) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:294) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:252) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:287) ~[liquibase-core-4.26.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1815) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1764) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:596) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1165) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:939) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:615) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.8.jar:3.1.8]
	at com.example.testliquibase.TestLiquibaseApplication.main(TestLiquibaseApplication.java:10) ~[classes/:na]
Caused by: org.postgresql.util.PSQLException: ERROR: relation "company" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292) ~[postgresql-42.6.0.jar:42.6.0]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464) ~[liquibase-core-4.26.0.jar:na]
	... 64 common frames omitted

2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : UPDATE SUMMARY
2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : Run:                          1
2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : Previously run:               0
2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : Filtered out:                 0
2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : -------------------------------
2024-03-22T10:19:01.294+05:30  INFO 8509 --- [           main] liquibase.util                           : Total change sets:            1
2024-03-22T10:19:01.295+05:30  INFO 8509 --- [           main] liquibase.util                           : Update summary generated
2024-03-22T10:19:01.297+05:30  INFO 8509 --- [           main] liquibase.command                        : Update command encountered an exception.
2024-03-22T10:19:01.306+05:30  INFO 8509 --- [           main] liquibase.lockservice                    : Successfully released change log lock
2024-03-22T10:19:01.309+05:30  INFO 8509 --- [           main] liquibase.command                        : Logging exception.
2024-03-22T10:19:01.310+05:30  INFO 8509 --- [           main] liquibase.ui                             : ERROR: Exception Details
2024-03-22T10:19:01.310+05:30  INFO 8509 --- [           main] liquibase.ui                             : ERROR: Exception Primary Class:  PSQLException
2024-03-22T10:19:01.310+05:30  INFO 8509 --- [           main] liquibase.ui                             : ERROR: Exception Primary Reason: ERROR: relation "company" already exists
2024-03-22T10:19:01.310+05:30  INFO 8509 --- [           main] liquibase.ui                             : ERROR: Exception Primary Source: PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1)
2024-03-22T10:19:01.310+05:30  INFO 8509 --- [           main] liquibase.command                        : Command execution complete
2024-03-22T10:19:01.314+05:30  WARN 8509 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
2024-03-22T10:19:01.315+05:30  INFO 8509 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-03-22T10:19:01.320+05:30  INFO 8509 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-03-22T10:19:01.324+05:30  INFO 8509 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-22T10:19:01.338+05:30  INFO 8509 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-22T10:19:01.355+05:30 ERROR 8509 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1768) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:596) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1165) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:939) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:615) ~[spring-context-6.0.16.jar:6.0.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-3.1.8.jar:3.1.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.8.jar:3.1.8]
	at com.example.testliquibase.TestLiquibaseApplication.main(TestLiquibaseApplication.java:10) ~[classes/:na]
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:304) ~[liquibase-core-4.26.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1815) ~[spring-beans-6.0.16.jar:6.0.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1764) ~[spring-beans-6.0.16.jar:6.0.16]
	... 18 common frames omitted
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.command.CommandScope.execute(CommandScope.java:253) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:1419) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:234) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:212) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:343) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:294) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:252) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:287) ~[liquibase-core-4.26.0.jar:na]
	... 20 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.command.CommandScope.execute(CommandScope.java:217) ~[liquibase-core-4.26.0.jar:na]
	... 36 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/001-initial.xml::1::test_liquibase_sabeeta:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:797) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:186) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:195) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:185) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:164) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:252) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.Scope.child(Scope.java:256) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89) ~[liquibase-core-4.26.0.jar:na]
	... 44 common frames omitted
Caused by: liquibase.exception.DatabaseException: ERROR: relation "company" already exists [Failed SQL: (0) CREATE TABLE public.company (id INTEGER NOT NULL, CONSTRAINT company_pkey PRIMARY KEY (id))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285) ~[liquibase-core-4.26.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755) ~[liquibase-core-4.26.0.jar:na]
	... 59 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "company" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292) ~[postgresql-42.6.0.jar:42.6.0]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464) ~[liquibase-core-4.26.0.jar:na]
	... 64 common frames omitted


Process finished with exit code 1

```

**Comment by SabeetaBhandari** [comment]
Hi team,

Just one update. As a workaround, I added the logicalFilePath in the changeset with existing value. After this the existing changeset is not getting picked up.

Like in above example adding logicalFilePath="classpath*:liquibase/changelogs/chnge1/change2/0001-initial.xml" fixes the problem.

I believe this should work in production as well.

**Comment by MalloD12** [comment]
Hi @SabeetaBhandari,

Could you please do us a favor by trying to reproduce this issue using the branch of #5727? We think it could fix this issue.

Thanks,
Daniel.

**Comment by adrian-velonis1** [comment]
[DOC INTERNAL] https://datical.atlassian.net/browse/PD-4479

**Comment by filipelautert** [comment]
This was addressed in PR #5727 (merged April 2024) which normalizes file paths for comparison, preventing already-run changesets from being re-executed after upgrades. Using `logicalFilePath` is also documented as a stable solution for this class of issues.

Closing this out — if you're still hitting this on a recent version, feel free to re-open.
